#!/usr/bin/env bash
# custom 404
# Update package list
apt-get update -y

# Install nginx
apt-get install nginx -y
service nginx start
echo "Hello World!" > /etc/nginx/html/index.html
echo -e "Ceci n'est pas une page\n" > /etc/nginx/html/404.html
# Create a custom configuration file for the redirection
echo "server {
    listen 80;
    listen [::]:80;
    root /etc/nginx/html;
    index index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html{
        root /etc/nginx/html;
    }

}" > /etc/nginx/sites-available/default
service nginx restart
