#!/usr/bin/env bash
#configure nginx server to listen for port 80
rm /ect/nginx/sites-enabled/default
ln -s /ect/nginx/sites-available/default /ect/nginx/sites-enabled/default
sudo service nginx restart
