#!/usr/bin/env bash
# displays the content of the file /etc/passwd, using the while loop
file="/etc/passwd"
exec 3<"$file"
while read -r line <&3; do
	username=$(echo "$line" | cut -d':' -f1)
	grpid=$(echo "$line" | cut -d':' -f4)
	userid=$(echo "$line" | cut -d':' -f3)
	Home=$(echo "$line" | cut -d':' -f6)
	cmd=$(echo "$line" | cut -d':' -f7)
	password=$(echo "$line" | cut -d':' -f2)
	useridinfo=$(echo "$line" | cut -d':' -f5)
	echo "The user $username is part of the $grpid gang, lives in $Home and rides $cmd. $userid's place is protected by the passcode $password, more info about the user here: $useridinfo"
done
