#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
apt-get update
apt-get install ufw
# Reset UFW rules to default and block all incoming traffic
sudo ufw reset
sudo ufw default deny incoming

# Allow incoming traffic on SSH (port 22), HTTPS (port 443), and HTTP (port 80)
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable UFW
sudo ufw enable
